artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: 'https://github.com/shubham953/Loantap_END_to_END_CI_CD_MlOps_AWS/raw/main/LoanTap.zip'
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation
  unzip_data_dir: artifacts/data_ingestion/LoanTap.csv
  STATUS_FILE: artifacts/data_validation/status.txt



data_transformation:
  root_dir: artifacts/data_transformation
  data_path: artifacts/feature_engineering/featured_data.csv



model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.joblib
  scaler_name: scaler.joblib



model_evaluation:
  root_dir: artifacts/model_evaluation
  test_data_path_x: artifacts/model_trainer/test_x.npy
  test_data_path_y: artifacts/model_trainer/test_y.npy
  
  model_path: artifacts/model_trainer/model.joblib
  metric_file_name: artifacts/model_evaluation/metrics.json

feature_engineering:
  root_dir: artifacts/feature_engineering
  data_path: artifacts\data_ingestion\LoanTap.csv

 
  